name: Release

on:
  workflow_dispatch:  # 手動実行のみに設定

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the site
        run: pnpm build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: MidraLab
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run deploy
